name: Keep Supabase Alive

on:
  schedule:
    - cron: "0 0 */3 * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API Endpoint
        run: |
          curl -X GET ${{ secrets.API_URL }}/api/recipes
        env:
          API_URL: ${{ secrets.API_URL }}
